pipeline:
  ## Build and Tests
  staging-build:
    image: node:12
    environment:
      - REACT_APP_HASURA_API_URL=https://api-graphql.staging.bonde.org/v1/graphql
      - REACT_APP_ADMIN_URL=https://admin-canary.staging.bonde.org/admin
      - REACT_APP_DOMAIN_CROSS_STORAGE=https://cross-storage.staging.bonde.org
    commands:
      - yarn global add pnpm
      - pnpm i
      - pnpm m run build
    when:
      event: [push]
  
  docker-staging-publish:
    image: plugins/docker
    repo: nossas/bonde-auth
    group: publishing
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_BRANCH/\//-}
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, support/*, develop]
      event: push

  ## Deploy on rancher cluster - Staging
  webhook-staging-deploy:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: auth/webhook
    group: deploying
    docker_image: nossas/bonde-auth:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]

  api-staging-deploy:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: auth/api
    group: deploying
    docker_image: nossas/bonde-auth:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]

  client-staging-deploy:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: auth/client
    group: deploying
    docker_image: nossas/bonde-auth:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]
