pipeline:
  ## Publish on docker hub

  webhook-auth-publish:
    image: plugins/docker
    repo: nossas/bonde-auth-webhook
    group: publishing
    secrets: [ docker_username, docker_password ]
    dockerfile: packages/webhook/Dockerfile
    tags:
      - ${DRONE_BRANCH/\//-}
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, support/*, develop]

  api-auth-publish:
    image: plugins/docker
    repo: nossas/bonde-auth-api
    group: publishing
    secrets: [ docker_username, docker_password ]
    dockerfile: packages/api/Dockerfile
    tags:
      - ${DRONE_BRANCH/\//-}
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, support/*, develop]

  ## Deploy on rancher cluster - Staging

  webhook-auth-staging-deploy:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: auth/webhook
    group: deploying
    docker_image: nossas/bonde-auth-webhook:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]

  api-auth-staging-deploy:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: auth/api
    group: deploying
    docker_image: nossas/bonde-auth-api:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]

  ## Deploy on rancher cluster - Production

  # PACKAGE-NAME-production-deploy:
  #   image: peloton/drone-rancher
  #   url: http://cluster.bonde.org
  #   service: auth/PACKAGE-NAME
  #   docker_image: "nossas/bonde-auth-PACKAGE-NAME:${DRONE_TAG##v}"
  #   timeout: 360
  #   group: deploy
  #   confirm: true
  #   secrets:
  #     - source: rancher_access_key_prod
  #       target: rancher_access_key
  #     - source: rancher_secret_key_prod
  #       target: rancher_secret_key
  #   when:
  #     status: success
  #     event: tag